# Generated by Django 2.1.2 on 2018-10-19 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_auto_20181019_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='ref_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
